# Generated by Django 2.2.4 on 2019-11-08 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='seguidores',
            field=models.ManyToManyField(blank=True, null=True, related_name='seguidores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
